from __future__ import annotations

import json
from pathlib import Path

from src.blender_ir.schema import BlenderSceneIR
from src.blender_ir.validator import validate_scene_ir


class BlenderCodeCompiler:
    def compile(self, ir: BlenderSceneIR, output_script: Path) -> Path:
        validate_scene_ir(ir)
        output_script.parent.mkdir(parents=True, exist_ok=True)
        ir_json = json.dumps(ir.to_dict(), indent=2)
        output_script.write_text(self._template(ir_json), encoding="utf-8")
        return output_script

    def _template(self, ir_json: str) -> str:
        return f'''# Auto-generated by editable 2D-to-Blender scene pipeline.
# Source of truth: embedded Blender Scene IR JSON. Edit IR, then recompile this script.
import json
import math
import sys
import traceback
from pathlib import Path

import bpy

IR = json.loads(r"""{ir_json}""")


def clear_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()
    for datablock in list(bpy.data.meshes):
        if datablock.users == 0:
            bpy.data.meshes.remove(datablock)
    for material in list(bpy.data.materials):
        if material.users == 0:
            bpy.data.materials.remove(material)


REQUIRED_COLLECTIONS = ["Room", "Furniture", "Lighting", "Camera", "ReconstructedMeshes", "ProceduralObjects"]


def log(message):
    print("[SceneAutoProducer]", message)


def ensure_collection(name, parent_name=None):
    collection = bpy.data.collections.get(name)
    created = collection is None
    if collection is None:
        collection = bpy.data.collections.new(name)
    if parent_name is None:
        if created:
            bpy.context.scene.collection.children.link(collection)
        return collection
    parent = ensure_collection(parent_name)
    if not any(child.name == collection.name for child in parent.children):
        parent.children.link(collection)
    return collection


def move_to_collection(obj, collection_name):
    collection = ensure_collection(collection_name)
    for old_collection in list(obj.users_collection):
        old_collection.objects.unlink(obj)
    collection.objects.link(obj)


def create_required_collections():
    ensure_collection("Room")
    for name in REQUIRED_COLLECTIONS:
        if name != "Room":
            ensure_collection(name, "Room")


def set_custom_properties(obj, spec):
    obj["source_object_id"] = spec.get("id", obj.name)
    obj["category"] = spec.get("category", "unknown")
    obj["generation_strategy"] = spec.get("metadata", {{}}).get("generation_strategy", spec.get("object_type", "unknown"))
    obj["iteration"] = spec.get("metadata", {{}}).get("iteration", IR["scene"].get("iteration", 0))


def create_material(spec):
    material = bpy.data.materials.new(spec["name"])
    material.use_nodes = True
    bsdf = material.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        base = bsdf.inputs.get("Base Color")
        roughness = bsdf.inputs.get("Roughness")
        metallic = bsdf.inputs.get("Metallic")
        alpha = bsdf.inputs.get("Alpha")
        if base:
            base.default_value = spec.get("base_color", [0.8, 0.8, 0.8, 1.0])
        if roughness:
            roughness.default_value = spec.get("roughness", 0.55)
        if metallic:
            metallic.default_value = spec.get("metallic", 0.0)
        if alpha:
            alpha.default_value = spec.get("alpha", 1.0)
    return material


def apply_transform(obj, transform):
    obj.location = transform.get("position", [0, 0, 0])
    obj.rotation_euler = transform.get("rotation_euler", [0, 0, 0])
    obj.scale = transform.get("scale", [1, 1, 1])


def assign_material(obj, material):
    if material and hasattr(obj.data, "materials"):
        obj.data.materials.clear()
        obj.data.materials.append(material)


def cube_part(name, dimensions, local_position, material, collection_name, parent=None, bevel=0.0, source_spec=None):
    bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, 0))
    obj = bpy.context.object
    obj.name = name
    obj.data.name = name + "_mesh"
    obj.dimensions = dimensions
    if parent:
        obj.parent = parent
    obj.location = local_position
    assign_material(obj, material)
    if source_spec:
        set_custom_properties(obj, source_spec)
    move_to_collection(obj, collection_name)
    if bevel > 0:
        modifier = obj.modifiers.new(name="editable_bevel", type="BEVEL")
        modifier.width = bevel
        modifier.segments = 2
        obj.modifiers.new(name="weighted_normals", type="WEIGHTED_NORMAL")
    return obj


def create_empty_parent(spec):
    empty = bpy.data.objects.new(spec["name"], None)
    bpy.context.scene.collection.objects.link(empty)
    move_to_collection(empty, spec["collection"])
    apply_transform(empty, spec["transform"])
    set_custom_properties(empty, spec)
    return empty


def create_table(spec, material):
    parent = create_empty_parent(spec)
    dims = spec["procedural"]["dimensions"]
    top_t = spec["procedural"].get("top_thickness", 0.06)
    leg_t = spec["procedural"].get("leg_thickness", 0.06)
    bevel = spec["procedural"].get("bevel", 0.0)
    width, depth, height = dims
    top_z = height / 2 - top_t / 2
    leg_z = -top_t / 2
    leg_h = max(0.05, height - top_t)
    cube_part(spec["id"] + "_top", [width, depth, top_t], [0, 0, top_z], material, spec["collection"], parent, bevel, spec)
    offsets = [
        ("FL", -width / 2 + leg_t, -depth / 2 + leg_t),
        ("FR", width / 2 - leg_t, -depth / 2 + leg_t),
        ("BL", -width / 2 + leg_t, depth / 2 - leg_t),
        ("BR", width / 2 - leg_t, depth / 2 - leg_t),
    ]
    for suffix, x, y in offsets:
        cube_part(spec["id"] + "_leg_" + suffix, [leg_t, leg_t, leg_h], [x, y, leg_z - leg_h / 2], material, spec["collection"], parent, bevel, spec)
    return parent


def create_cabinet(spec, material):
    parent = create_empty_parent(spec)
    dims = spec["procedural"]["dimensions"]
    width, depth, height = dims
    t = spec["procedural"].get("board_thickness", 0.045)
    bevel = spec["procedural"].get("bevel", 0.0)
    shelf_count = spec["procedural"].get("shelf_count", 3)
    cube_part(spec["id"] + "_left_side", [t, depth, height], [-width / 2 + t / 2, 0, 0], material, spec["collection"], parent, bevel, spec)
    cube_part(spec["id"] + "_right_side", [t, depth, height], [width / 2 - t / 2, 0, 0], material, spec["collection"], parent, bevel, spec)
    cube_part(spec["id"] + "_top", [width, depth, t], [0, 0, height / 2 - t / 2], material, spec["collection"], parent, bevel, spec)
    cube_part(spec["id"] + "_bottom", [width, depth, t], [0, 0, -height / 2 + t / 2], material, spec["collection"], parent, bevel, spec)
    for index in range(1, shelf_count + 1):
        z = -height / 2 + index * height / (shelf_count + 1)
        cube_part(f"{{spec['id']}}_shelf_{{index:02d}}", [width - 2 * t, depth * 0.94, t], [0, 0, z], material, spec["collection"], parent, bevel, spec)
    return parent


def create_box_procedural(spec, material):
    parent = create_empty_parent(spec)
    dims = spec["procedural"].get("dimensions", spec["dimensions"])
    cube_part(spec["id"] + "_body", dims, [0, 0, 0], material, spec["collection"], parent, spec["procedural"].get("bevel", 0.0), spec)
    return parent


def create_primitive(spec, material):
    primitive_type = spec.get("primitive", {{}}).get("type", "cube")
    if primitive_type == "plane":
        bpy.ops.mesh.primitive_plane_add(size=1)
    elif primitive_type == "cylinder":
        bpy.ops.mesh.primitive_cylinder_add(vertices=48, radius=0.5, depth=1.0)
    else:
        bpy.ops.mesh.primitive_cube_add(size=1)
    obj = bpy.context.object
    obj.name = spec["name"]
    obj.dimensions = spec["dimensions"]
    apply_transform(obj, spec["transform"])
    assign_material(obj, material)
    set_custom_properties(obj, spec)
    move_to_collection(obj, spec["collection"])
    return obj


def create_asset_proxy(spec, material):
    category = spec.get("category", "object")
    if category == "chair":
        parent = create_empty_parent(spec)
        width, depth, height = spec["dimensions"]
        seat_h = min(0.10, height * 0.12)
        leg_t = min(0.06, max(0.035, width * 0.10))
        seat_z = -height / 2 + height * 0.45
        cube_part(spec["id"] + "_seat", [width, depth, seat_h], [0, 0, seat_z], material, spec["collection"], parent, 0.012, spec)
        cube_part(spec["id"] + "_back", [width, leg_t, height * 0.52], [0, depth / 2 - leg_t / 2, seat_z + height * 0.28], material, spec["collection"], parent, 0.012, spec)
        for suffix, x, y in [
            ("FL", -width / 2 + leg_t, -depth / 2 + leg_t),
            ("FR", width / 2 - leg_t, -depth / 2 + leg_t),
            ("BL", -width / 2 + leg_t, depth / 2 - leg_t),
            ("BR", width / 2 - leg_t, depth / 2 - leg_t),
        ]:
            cube_part(spec["id"] + "_leg_" + suffix, [leg_t, leg_t, height * 0.45], [x, y, -height / 2 + height * 0.225], material, spec["collection"], parent, 0.008, spec)
        return parent
    if category == "lamp":
        parent = create_empty_parent(spec)
        width, depth, height = spec["dimensions"]
        cube_part(spec["id"] + "_base", [width, depth, height * 0.08], [0, 0, -height / 2 + height * 0.04], material, spec["collection"], parent, 0.01, spec)
        bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=min(width, depth) * 0.08, depth=height * 0.58, location=(0, 0, 0))
        stem = bpy.context.object
        stem.name = spec["id"] + "_stem"
        stem.parent = parent
        stem.location = [0, 0, -height * 0.10]
        assign_material(stem, material)
        set_custom_properties(stem, spec)
        move_to_collection(stem, spec["collection"])
        cube_part(spec["id"] + "_shade", [width * 0.85, depth * 0.85, height * 0.26], [0, 0, height * 0.28], material, spec["collection"], parent, 0.015, spec)
        return parent
    obj = create_primitive({{**spec, "primitive": {{"type": "cube"}}}}, material)
    obj.name = spec["name"] + "_asset_proxy"
    return obj


def import_or_placeholder(spec, material):
    path = spec.get("source_path")
    if spec["object_type"] == "asset" and spec.get("asset"):
        path = spec["asset"].get("path")
    imported = []
    if path and Path(path).exists():
        suffix = Path(path).suffix.lower()
        before = set(bpy.context.scene.objects)
        if suffix == ".obj":
            bpy.ops.wm.obj_import(filepath=path)
        elif suffix in {{".glb", ".gltf"}}:
            bpy.ops.import_scene.gltf(filepath=path)
        elif suffix == ".fbx":
            bpy.ops.import_scene.fbx(filepath=path)
        imported = [obj for obj in bpy.context.scene.objects if obj not in before]
    if not imported:
        if spec["object_type"] == "asset":
            return create_asset_proxy(spec, material)
        obj = create_primitive({{**spec, "primitive": {{"type": "cube"}}}}, material)
        obj.name = spec["name"] + "_mesh_proxy"
        return obj
    parent = create_empty_parent(spec)
    for index, obj in enumerate(imported, start=1):
        obj.name = spec["id"] + f"_part_{{index:02d}}"
        obj.parent = parent
        assign_material(obj, material)
        set_custom_properties(obj, spec)
        move_to_collection(obj, spec["collection"])
    return parent


def create_object(spec, materials):
    material = materials.get(spec["material_id"])
    kind = spec["object_type"]
    if kind == "procedural":
        procedural_kind = spec["procedural"].get("kind", "box")
        if procedural_kind == "table":
            return create_table(spec, material)
        if procedural_kind == "cabinet":
            return create_cabinet(spec, material)
        return create_box_procedural(spec, material)
    if kind == "primitive":
        return create_primitive(spec, material)
    return import_or_placeholder(spec, material)


def setup_camera(camera_spec):
    bpy.ops.object.camera_add(location=camera_spec["position"], rotation=camera_spec["rotation_euler"])
    camera = bpy.context.object
    camera.name = camera_spec["name"]
    camera.data.lens = camera_spec.get("focal_length", 35.0)
    camera.data.sensor_width = camera_spec.get("sensor_width", 32.0)
    bpy.context.scene.camera = camera
    move_to_collection(camera, "Camera")


def setup_lights(light_specs):
    for spec in light_specs:
        data = bpy.data.lights.new(spec["name"], type=spec.get("light_type", "AREA"))
        data.energy = spec.get("energy", 400.0)
        if hasattr(data, "size"):
            data.size = spec.get("size", 3.0)
        light = bpy.data.objects.new(spec["name"], data)
        bpy.context.scene.collection.objects.link(light)
        light.location = spec["position"]
        light.rotation_euler = spec.get("rotation_euler", [0, 0, 0])
        move_to_collection(light, "Lighting")


def export_scene(scene_spec):
    for export in scene_spec.get("exports", []):
        export = export.lower()
        output_blend = Path(scene_spec["output_blend"])
        out_path = output_blend.with_suffix("." + export)
        if export == "glb":
            bpy.ops.export_scene.gltf(filepath=str(out_path), export_format="GLB")
        elif export == "fbx":
            bpy.ops.export_scene.fbx(filepath=str(out_path))
        elif export == "obj":
            bpy.ops.wm.obj_export(filepath=str(out_path))


def render_preview(scene_spec):
    preview = scene_spec.get("preview_render")
    if not preview:
        return
    Path(preview).parent.mkdir(parents=True, exist_ok=True)
    bpy.context.scene.render.filepath = preview
    bpy.context.scene.render.resolution_x = 1280
    bpy.context.scene.render.resolution_y = 900
    bpy.ops.render.render(write_still=True)


def main():
    log("clearing scene")
    clear_scene()
    create_required_collections()
    for collection_name in IR["scene"].get("collections", []):
        ensure_collection(collection_name)
    materials = {{material["id"]: create_material(material) for material in IR["materials"]}}
    for spec in IR["objects"]:
        log("creating " + spec["id"])
        create_object(spec, materials)
    setup_camera(IR["camera"])
    setup_lights(IR["lights"])
    Path(IR["scene"]["output_blend"]).parent.mkdir(parents=True, exist_ok=True)
    log("saving blend to " + IR["scene"]["output_blend"])
    bpy.ops.wm.save_as_mainfile(filepath=IR["scene"]["output_blend"])
    export_scene(IR["scene"])
    render_preview(IR["scene"])


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
        sys.exit(1)
'''
